import type { LucideIcon } from "lucide-react";
import {
  Atom,
  Banknote,
  Bitcoin,
  Bot,
  Briefcase,
  Building,
  Calculator,
  CalendarDays,
  Car,
  ChartColumn,
  Clock,
  CreditCard,
  Dumbbell,
  FlaskConical,
  Fuel,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HeartPulse,
  House,
  Info,
  Landmark,
  Lightbulb,
  PawPrint,
  Percent,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Ruler,
  Scale,
  ShieldCheck,
  ShoppingCart,
  Sigma,
  TrendingUp,
  Wallet,
} from "lucide-react";

// Icons the admin can pick for home page category tiles (/admin/homepage).
// Keys are stored in the homepage settings, so keep existing keys stable.
export const HOME_ICONS: Record<string, { label: string; icon: LucideIcon }> = {
  calculator: { label: "Calculator", icon: Calculator },
  banknote: { label: "Money", icon: Banknote },
  landmark: { label: "Bank / Loan", icon: Landmark },
  house: { label: "House / Mortgage", icon: House },
  building: { label: "Building / Real Estate", icon: Building },
  receipt: { label: "Receipt / Tax", icon: Receipt },
  "trending-up": { label: "Growth / Investing", icon: TrendingUp },
  "piggy-bank": { label: "Piggy Bank / Savings", icon: PiggyBank },
  wallet: { label: "Wallet / Budget", icon: Wallet },
  "shield-check": { label: "Shield / Insurance", icon: ShieldCheck },
  car: { label: "Car", icon: Car },
  bitcoin: { label: "Crypto", icon: Bitcoin },
  briefcase: { label: "Briefcase / Salary", icon: Briefcase },
  "credit-card": { label: "Credit Card / Debt", icon: CreditCard },
  chart: { label: "Chart / Business", icon: ChartColumn },
  percent: { label: "Percent / Interest", icon: Percent },
  "graduation-cap": { label: "Education", icon: GraduationCap },
  sigma: { label: "Math", icon: Sigma },
  "heart-pulse": { label: "Health", icon: HeartPulse },
  dumbbell: { label: "Fitness", icon: Dumbbell },
  flask: { label: "Chemistry", icon: FlaskConical },
  atom: { label: "Physics", icon: Atom },
  ruler: { label: "Measurement", icon: Ruler },
  scale: { label: "Scale / Weight", icon: Scale },
  hammer: { label: "Construction", icon: Hammer },
  "paw-print": { label: "Pets", icon: PawPrint },
  calendar: { label: "Date", icon: CalendarDays },
  clock: { label: "Time", icon: Clock },
  fuel: { label: "Fuel", icon: Fuel },
  plane: { label: "Travel", icon: Plane },
  "shopping-cart": { label: "Shopping", icon: ShoppingCart },
  gift: { label: "Gift", icon: Gift },
  globe: { label: "Globe / Currency", icon: Globe },
  repeat: { label: "Conversion", icon: Repeat },
  info: { label: "Everyday Life", icon: Info },
  lightbulb: { label: "Ideas / Energy", icon: Lightbulb },
  bot: { label: "AI Tools", icon: Bot },
};

// Default icon for a category when the admin hasn't picked one, matched on its slug.
const SLUG_RULES: [RegExp, string][] = [
  [/crypto|forex/, "bitcoin"],
  [/currency|exchange/, "globe"],
  [/mortgage|home/, "house"],
  [/real-estate|property/, "building"],
  [/loan/, "landmark"],
  [/tax|paycheck/, "receipt"],
  [/invest|stock|fund|bond/, "trending-up"],
  [/retire|pension/, "piggy-bank"],
  [/budget/, "wallet"],
  [/insurance/, "shield-check"],
  [/car|vehicle|auto/, "car"],
  [/salary|income|wage/, "briefcase"],
  [/credit|debt/, "credit-card"],
  [/business/, "chart"],
  [/interest|savings/, "percent"],
  [/student|education|college/, "graduation-cap"],
  [/math|algebra|statistic/, "sigma"],
  [/health|bmi/, "heart-pulse"],
  [/finance|money/, "banknote"],
];

export function iconKeyForSlug(slug: string): string {
  return SLUG_RULES.find(([re]) => re.test(slug))?.[1] ?? "calculator";
}

export function homeIcon(key: string, slug: string): LucideIcon {
  return (HOME_ICONS[key] ?? HOME_ICONS[iconKeyForSlug(slug)] ?? HOME_ICONS.calculator).icon;
}
